version: '3'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-antipov}
      POSTGRES_USER: ${DB_USER:-retmix}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
    volumes:
      - dbData:/var/lib/postgres
    ports:
      - "${PORT_DB:-5432}:5432"
    depends_on:
      - java
    networks:
      - retmix

  java:
    build:
      context: .
      dockerfile: ./image/Dockerfile
    networks:
      - retmix
    restart: unless-stopped

volumes:
  dbData:
   driver: local

networks:
  retmix:
    driver: bridge